name: PHP docker CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker compose build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Start containers
        
        run: docker compose up -d --build

      - name: Wait for services
       
        run: sleep 15

      - name: Check containers
        
        run: docker ps

      - name: Install dependencies
        run: docker compose exec -T php composer install --no-interaction --no-progress

      - name: Run PHPUnit tests
        run: docker compose exec -T php vendor/bin/phpunit tests

      - name: Show logs on error
        
        if: failure()
        run: docker compose logs

      - name: Stop containers
        if: always()
        run: docker compose down